-- Database Schema for Banking Lab
-- Created on 16-FEB-2026
-- Version: 1.0

-- Create Customers Table
CREATE TABLE banking_customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(100),
    account_type VARCHAR2(20),
    balance NUMBER(15,2),
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert Sample Data for Demo
INSERT INTO banking_customers (full_name, account_type, balance) 
VALUES ('Asia Corporate Account', 'Business', 250000.00);

COMMIT;

SELECT * FROM banking_customers;
